name: daydreamxi
favicon: null
layout_spectrum: 0.20174346887506545
typography_spectrum: 0.5361081559676677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.979879813734442
  lightness: 0.269519139546901
  saturation: 0.6428988217376173
  rhythmicContrast: 0.5351760168559849
purpose: []
